swagger: '2.0'
info:
  version: '1.0'
  title: "Test api"
  description: Hello World
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: ssc-project.herokuapp.com
basePath: /
schemes:
- https
paths:
  /home:
    get:
      tags:
        - home
      summary: page displayed after login
      description: 'you do a get to display all the informations in the site'
      operationId: getHome
      
           
      responses:
        '404':
          description: Server not found
     
    put:
      tags:
        - home
      summary: to delete or to modify a comment or a post
      description: 'you can submit a comment under a post'
      operationId: updateHome
      
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Server not found
        '405':
          description: Validation exception
    
    post:
      tags:
        - home
      summary: Add a new comment or post 
      description: 'you can post a post or a comment in the home page'
      operationId: postHome
      
           
      responses:
        '405':
          description: Invalid input